# Generated by Django 3.1.4 on 2020-12-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0002_auto_20201216_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preand',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name_uk',
            field=models.CharField(max_length=255, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weakhand',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default=0, verbose_name='Weak hand'),
        ),
    ]
