# Generated by Django 3.1.4 on 2020-12-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0003_auto_20201217_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ex_video',
            options={'verbose_name_plural': 'Exercise video'},
        ),
        migrations.AlterModelOptions(
            name='frames',
            options={'verbose_name_plural': 'Frames'},
        ),
        migrations.AlterModelOptions(
            name='obj',
            options={'verbose_name_plural': 'Object list'},
        ),
        migrations.AlterModelOptions(
            name='raw_video',
            options={'verbose_name_plural': 'Raw video'},
        ),
        migrations.AlterModelOptions(
            name='seg_video',
            options={'verbose_name_plural': 'Segment video'},
        ),
        migrations.AlterModelTable(
            name='ex_video',
            table='Ex_video',
        ),
        migrations.AlterModelTable(
            name='frames',
            table='Frames',
        ),
        migrations.AlterModelTable(
            name='obj',
            table='Obj',
        ),
        migrations.AlterModelTable(
            name='raw_video',
            table='Raw_video',
        ),
        migrations.AlterModelTable(
            name='seg_video',
            table='Seg_video',
        ),
    ]
