# Generated by Django 3.1.4 on 2020-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0004_auto_20201217_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weakhand',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=50, verbose_name='Weak hand'),
        ),
    ]
