# Generated by Django 3.1.4 on 2020-12-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0006_patient_prehand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sod',
            field=models.CharField(max_length=500, verbose_name='Disease status'),
        ),
    ]
