# Generated by Django 3.1.4 on 2021-01-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0008_auto_20210113_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_video',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
