# Generated by Django 3.1.4 on 2021-01-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0009_auto_20210113_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='obj',
        ),
    ]
