# Generated by Django 3.1.5 on 2021-01-19 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0010_remove_annotation_obj'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='annotation',
            table='frame_annotation',
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.FileField(upload_to='acceleration')),
                ('elanPath', models.FileField(upload_to='elan')),
                ('raw_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.raw_video')),
            ],
            options={
                'verbose_name_plural': 'Gyroscope',
                'db_table': 'gyroscope',
            },
        ),
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.FileField(upload_to='acceleration')),
                ('elanPath', models.FileField(upload_to='elan')),
                ('raw_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.raw_video')),
            ],
            options={
                'verbose_name_plural': 'Acceleration',
                'db_table': 'acceleration',
            },
        ),
    ]
