# Generated by Django 3.1.4 on 2021-01-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0011_auto_20210119_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='seg_video',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frames',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raw_video',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raw_video',
            name='position',
            field=models.CharField(choices=[('Head', 'Head'), ('Chest', 'Chest')], default=0, max_length=50, verbose_name='Camera position'),
        ),
    ]
