# Generated by Django 3.1.4 on 2021-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0012_auto_20210124_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='raw_video',
            field=models.ManyToManyField(through='frame.Ex_video', to='frame.Raw_video'),
        ),
    ]
