# Generated by Django 3.1.4 on 2021-01-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0013_exercise_raw_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='raw_video',
            field=models.ManyToManyField(related_name='raw_video', through='frame.Ex_video', to='frame.Raw_video'),
        ),
    ]
