# Generated by Django 3.1.4 on 2021-01-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0014_auto_20210125_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='Path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='elanPath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='jsonPath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gyroscope',
            name='Path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gyroscope',
            name='elanPath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
