# Generated by Django 3.1.4 on 2021-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0015_auto_20210128_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_video',
            name='position',
            field=models.CharField(choices=[('Head', 'Head'), ('Chest', 'Chest')], default='Head', max_length=50, verbose_name='Camera position'),
        ),
    ]
